// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NpcManager.Data;

#nullable disable

namespace NpcManager.Migrations
{
    [DbContext(typeof(NpcManagerContext))]
    [Migration("20221108005327_Primeira")]
    partial class Primeira
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NpcManager.Models.Autenticidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autenticidade");
                });

            modelBuilder.Entity("NpcManager.Models.Experiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experiencia");
                });

            modelBuilder.Entity("NpcManager.Models.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AutenticidadeDoisId")
                        .HasColumnType("int");

                    b.Property<int?>("AutenticidadeTresId")
                        .HasColumnType("int");

                    b.Property<int?>("AutenticidadeUmId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienciaDoisId")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienciaUmId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrigemId")
                        .HasColumnType("int");

                    b.Property<string>("Retrato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutenticidadeDoisId");

                    b.HasIndex("AutenticidadeTresId");

                    b.HasIndex("AutenticidadeUmId");

                    b.HasIndex("ExperienciaDoisId");

                    b.HasIndex("ExperienciaUmId");

                    b.HasIndex("OrigemId");

                    b.ToTable("Npc");
                });

            modelBuilder.Entity("NpcManager.Models.Origem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Origem");
                });

            modelBuilder.Entity("NpcManager.Models.Npc", b =>
                {
                    b.HasOne("NpcManager.Models.Autenticidade", "AutenticidadeDois")
                        .WithMany()
                        .HasForeignKey("AutenticidadeDoisId");

                    b.HasOne("NpcManager.Models.Autenticidade", "AutenticidadeTres")
                        .WithMany()
                        .HasForeignKey("AutenticidadeTresId");

                    b.HasOne("NpcManager.Models.Autenticidade", "AutenticidadeUm")
                        .WithMany()
                        .HasForeignKey("AutenticidadeUmId");

                    b.HasOne("NpcManager.Models.Experiencia", "ExperienciaDois")
                        .WithMany()
                        .HasForeignKey("ExperienciaDoisId");

                    b.HasOne("NpcManager.Models.Experiencia", "ExperienciaUm")
                        .WithMany()
                        .HasForeignKey("ExperienciaUmId");

                    b.HasOne("NpcManager.Models.Origem", "Origem")
                        .WithMany()
                        .HasForeignKey("OrigemId");

                    b.Navigation("AutenticidadeDois");

                    b.Navigation("AutenticidadeTres");

                    b.Navigation("AutenticidadeUm");

                    b.Navigation("ExperienciaDois");

                    b.Navigation("ExperienciaUm");

                    b.Navigation("Origem");
                });
#pragma warning restore 612, 618
        }
    }
}
